---
refresh_interval: 0.1 # seconds
max_price: 1900 # GBP
urls:
  - https://www.novatech.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-turbo-24gb-gddr6x-graphics-card/gv-n3090turbo-24gd.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3090-ventus-3x-oc-24gb-gddr6x-graphics-card/rtx3090ventus3x24goc.html
  - https://www.novatech.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-vision-oc-24gb-gddr6x-graphics-card/gv-n3090visionoc-24gd.html
  - https://www.novatech.co.uk/products/zotac-nvidia-geforce-rtx-3090-trinity-gaming-24gb-gddr6x-graphics-card/zt-a30900d-10p.html
  - https://www.novatech.co.uk/products/evga-nvidia-geforce-rtx-3090-ftw3-ultra-gaming-24gb-gddr6x-graphics-card/24g-p5-3987-kr.html
  - https://www.novatech.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-aorus-master-24gb-gddr6x-graphics-card/gv-n3090aorusm-24gd.html
  - https://www.novatech.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-aorus-xtreme-24gb-gddr6x-graphics-card/gv-n3090aorusx-24gd.html
  - https://www.novatech.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-gaming-oc-24gb-gddr6x-graphics-card/gv-n3090gamingoc-24gd.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3090-gaming-x-trio-24gb-gddr6x-graphics-card/rtx3090gamingxtrio24g.html
  - https://www.scan.co.uk/products/asus-nvidia-geforce-rtx-3090-tuf-gaming-oc-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/asus-nvidia-geforce-rtx-3090-rog-strix-oc-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/evga-nvidia-geforce-rtx-3090-xc3-gaming-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz-gpu
  - https://www.scan.co.uk/products/asus-nvidia-geforce-rtx-3090-tuf-gaming-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/evga-nvidia-geforce-rtx-3090-xc3-black-gaming-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395m
  - https://www.scan.co.uk/products/palit-nvidia-geforce-rtx-3090-gamingpro-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz-gpu
  - https://www.scan.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-eagle-oc-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/palit-nvidia-geforce-rtx-3090-gamerock-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz-gpu
  - https://www.scan.co.uk/products/evga-nvidia-geforce-rtx-3090-xc3-ultra-gaming-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395m
  - https://www.scan.co.uk/products/gigabyte-geforce-rtx-3090-vision-oc-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410mhz-gpu-175
  - https://www.scan.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-eagle-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410mhz-gpu
  - https://www.scan.co.uk/products/zotac-nvidia-geforce-rtx-3090-trinity-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/palit-nvidia-geforce-rtx-3090-gamerock-oc-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz-g
  - https://www.scan.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-gaming-oc-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/msi-nvidia-geforce-rtx-3090-gaming-x-trio-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410mhz-1
  - https://www.scan.co.uk/products/palit-nvidia-geforce-rtx-3090-gamingpro-oc-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz
  - https://www.scan.co.uk/products/msi-nvidia-geforce-rtx-3090-ventus-3x-oc-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/msi-nvidia-geforce-rtx-3090-suprim-x-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410mhz-gpu
  - https://www.scan.co.uk/products/asus-nvidia-geforce-rtx-3090-rog-strix-24gb-gddr6x-ray-tracing-graphics-card
  - https://www.scan.co.uk/products/evga-nvidia-geforce-rtx-3090-ftw3-ultra-gaming-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395
  - https://www.scan.co.uk/products/gigabyte-aorus-nvidia-geforce-rtx-3090-master-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410m
  - https://www.scan.co.uk/products/gigabyte-nvidia-geforce-rtx-3090-turbo-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410mhz-gpu
  - https://www.scan.co.uk/products/pny-geforce-rtx-3090-24gb-xlr8-gaming-epic-x-rgb-triple-fan-graphics-card
  - https://www.scan.co.uk/products/evga-nvidia-geforce-rtx-3090-ftw3-gaming-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz-gp
  - https://www.scan.co.uk/products/gigabyte-aorus-nvidia-geforce-rtx-3090-xtreme-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1410m
  - https://www.scan.co.uk/products/pny-nvidia-geforce-rtx-3090-epic-x-rgb-xlr8-24gb-gddr6x-ray-tracing-graphics-card-10496-core-1395mhz
  - https://www.amazon.co.uk/MSI-GeForce-SUPRIM-Gaming-Graphics/dp/B08LTJVGYS
  - https://www.amazon.co.uk/GeForce-RTX-3090-Founders-Graphics/dp/B08HR6ZBYJ
  - https://www.amazon.co.uk/Gigabyte-AORUS-GeForce-MASTER-Graphics/dp/B08KH7R4FQ
  - https://www.amazon.co.uk/MSI-GeForce-3090-Gaming-Trio/dp/B08HM6D7TM
  - https://www.amazon.co.uk/Gigabyte-GeForce-3090-VISION-Graphics/dp/B08MDC8J27
  - https://www.amazon.co.uk/Gigabyte-GeForce-GAMING-GDDR6X-Graphics/dp/B08HLYQ9XL
  - https://www.amazon.co.uk/ASUS-Graphics-reliability-performance-TUF-RTX3090-24G-GAMING/dp/B08HN4FLFJ
  - https://www.amazon.co.uk/ASUS-Graphics-Axial-tech-pressure-ROG-STRIX-RTX3090-24G-GAMING/dp/B08HN642LY
  - https://www.amazon.co.uk/PNY-GeForce-Gaming-EPIC-X-Graphics/dp/B08HBQWBHH
  - https://www.amazon.co.uk/EVGA-GeForce-24G-P5-3975-KR-Cooling-Backplate/dp/B08HGTNDL4
...
