---
refresh_interval: 0.1 # seconds
max_price: 570 # GBP
urls:
 - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3060-gaming-x-trio-12gb-gddr6-graphics-card/rtx3060gamingxtrio12g.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-12-gb-gaming-x-graphics-card-10220978-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-12-gb-ventus-2x-graphics-card-10221051-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-12-gb-ventus-3x-oc-graphics-card-10220976-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-12-gb-eagle-oc-graphics-card-10220555-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-12-gb-vision-oc-graphics-card-10221312-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-12-gb-ventus-2x-oc-graphics-card-10220926-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3060-12-gb-xlr8-gaming-revel-epic-x-rgb-edition-graphics-card-10220462-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-12-gb-gaming-oc-graphics-card-10220556-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3060-12-gb-uprising-edition-graphics-card-10220461-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-12-gb-gaming-x-trio-graphics-card-10220959-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3060-12-gb-rog-strix-gaming-oc-edition-graphics-card-10221040-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3060-12-gb-rog-strix-gaming-graphics-card-10221046-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3060-12-gb-xlr8-gaming-revel-edition-graphics-card-10221315-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3060-12-gb-tuf-gaming-oc-edition-graphics-card-10221045-pdt.html
 - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3060-12-gb-tuf-gaming-graphics-card-10221047-pdt.html
 - https://www.ebuyer.com/1139155-zotac-geforce-rtx-3060-12gb-amp-white-edition-ampere-graphics-card-zt-a30600f-10p
 - https://www.ebuyer.com/1142162-asus-geforce-rtx-3060-12gb-rog-strix-oc-ampere-graphics-card-rog-strix-rtx3060-o12g-gaming
 - https://www.ebuyer.com/1138914-pny-geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-ampere-graphics-card-vcg306012dfxppb
 - https://www.ebuyer.com/1140150-msi-geforce-rtx-3060-12gb-gaming-x-ampere-graphics-card-rtx-3060-gaming-x-12g
 - https://www.ebuyer.com/1142163-asus-geforce-rtx-3060-12gb-rog-strix-ampere-graphics-card-rog-strix-rtx3060-12g-gaming
 - https://www.ebuyer.com/1139157-zotac-geforce-rtx-3060-12gb-twin-edge-ampere-graphics-card-zt-a30600e-10m
 - https://www.ebuyer.com/1140151-msi-geforce-rtx-3060-12gb-ventus-3x-oc-ampere-graphics-card-rtx-3060-ventus-3x-12g-oc
 - https://www.ebuyer.com/1141627-palit-geforce-rtx-3060-12gb-dual-ampere-graphics-card-ne63060019k9-190ad
 - https://www.ebuyer.com/1142117-gigabyte-geforce-rtx-3060-12gb-gaming-oc-ampere-graphics-card-gv-n3060gaming-oc-12gd
 - https://www.ebuyer.com/1142164-asus-geforce-rtx-3060-12gb-tuf-gaming-oc-ampere-graphics-card-tuf-rtx3060-o12g-gaming
 - https://www.ebuyer.com/1142871-palit-geforce-rtx-3060-12gb-stormx-oc-ampere-graphics-card-ne63060s19k9-190af
 - https://www.ebuyer.com/1138915-pny-geforce-rtx-3060-12gb-uprising-edition-ampere-graphics-card-vcg306012dfmpb
 - https://www.ebuyer.com/1140152-msi-geforce-rtx-3060-12gb-ventus-2x-oc-ampere-graphics-card-rtx-3060-ventus-2x-12g-oc
 - https://www.ebuyer.com/1142118-gigabyte-geforce-rtx-3060-12gb-eagle-oc-ampere-graphics-card-gv-n3060eagle-oc-12gd
 - https://www.ebuyer.com/1142168-asus-geforce-rtx-3060-12gb-dual-ampere-graphics-card-dual-rtx3060-12g
 - https://www.ebuyer.com/1142872-palit-geforce-rtx-3060-12gb-stormx-ampere-graphics-card-ne63060019k9-190af
 - https://www.ebuyer.com/1142992-gigabyte-geforce-rtx-3060-12gb-aorus-elite-ampere-graphics-card-gv-n3060aorus-e-12gd
 - https://www.ebuyer.com/1143088-evga-geforce-rtx-3060-12gb-xc-gaming-ampere-graphics-card-12g-p5-3657-kr
 - https://www.ebuyer.com/1139156-zotac-geforce-rtx-3060-12gb-twin-edge-oc-ampere-graphics-card-zt-a30600h-10m
 - https://www.ebuyer.com/1140149-msi-geforce-rtx-3060-12gb-gaming-x-trio-ampere-graphics-card-rtx-3060-gaming-x-trio-12g
 - https://www.ebuyer.com/1140800-pny-geforce-rtx-3060-12gb-xlr8-gaming-revel-epic-x-single-fan-ampere-vcg306012sfxppb
 - https://www.ebuyer.com/1141626-palit-geforce-rtx-3060-12gb-dual-oc-ampere-graphics-card-ne63060t19k9-190ad
 - https://www.ebuyer.com/1142116-gigabyte-geforce-rtx-3060-12gb-vision-oc-ampere-graphics-card-gv-n3060vision-oc-12gd
 - https://www.ebuyer.com/1142119-gigabyte-geforce-rtx-3060-12gb-eagle-ampere-graphics-card-gv-n3060eagle-12gd
 - https://www.ebuyer.com/1142166-asus-geforce-rtx-3060-12gb-tuf-gaming-ampere-graphics-card-tuf-rtx3060-12g-gaming
...
