---
refresh_interval: 0.10 # seconds
max_price: 650 # GBP
urls:
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-suprim-x-8gb-gddr6-graphics-card/rtx30708gbsuprimx8g.html
  - https://www.novatech.co.uk/products/asus-nvidia-geforce-rtx-3070-dual-oc-8gb-gddr6-graphics-card/dual-rtx3070-o8g.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-graphics-card/rtx3070gamingxtrio.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-graphics-card/rtx3070ventus2xoc.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-graphics-card/rtx3070ventus3xoc.html
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-GAMING-Graphics/dp/B08KHL21CV
  - https://www.amazon.co.uk/ZOTAC-GAMING-GEFORCE-White-Graphics/dp/B08P7ZKQPP
  - https://www.amazon.co.uk/MSI-GeForce-SUPRIM-Gaming-Graphics/dp/B08P37HYZM
  - https://www.amazon.co.uk/MSI-GeForce-GAMING-Gaming-Graphics/dp/B08LNPPCWJ
  - https://www.amazon.co.uk/Gigabyte-AORUS-GeForce-MASTER-Graphics/dp/B08LNY8P5L
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-EAGLE-Graphics/dp/B08KHL2J5X
  - https://www.amazon.co.uk/ASUS-DisplayPort-Axial-tech-Protective-Backplate/dp/B08L8LG4M3
  - https://www.amazon.co.uk/Zotac-GAMING-GEFORCE-3070-HOLO/dp/B08R427DMQ
  - https://www.amazon.co.uk/GIGABYTE-Graphics-WINDFORCE-GV-N3070VISION-OC-8GD/dp/B08M13DXSZ
...
