---
refresh_interval: 2 # seconds
max_price: 900 # GBP
urls:
- https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-radeon-rx-6800-16-gb-gaming-oc-graphics-card-10219249-pdt.html # £678
- https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-radeon-rx-6800-16-gb-aorus-master-graphics-card-10220725-pdt.html # £750
...
