---
refresh_interval: 0.1 # seconds
max_price: 770 # GBP
urls:
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-graphics-card/rtx3070ventus2xoc.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-eagle-graphics-card-10217336-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-dual-graphics-card-10215777-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-ventus-2x-oc-graphics-card-10217083-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-gaming-oc-graphics-card-10216240-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-eagle-oc-graphics-card-10216239-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-vision-oc-graphics-card-10218742-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-dual-oc-graphics-card-10215776-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-rog-strix-gaming-oc-graphics-card-10215770-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-rog-strix-gaming-graphics-card-10215775-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-tuf-oc-gaming-graphics-card-10217338-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-gaming-x-trio-graphics-card-10217077-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-suprim-graphics-card-10220317-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-ventus-3x-oc-graphics-card-10217078-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-aorus-master-graphics-card-10218741-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3070-8-gb-xlr8-gaming-revel-edition-graphics-card-10218690-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-10-gb-rog-strix-oc-graphics-card-white-10220919-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-suprim-x-graphics-card-10219343-pdt.html
  - https://www.ebuyer.com/1126975-msi-geforce-rtx-3070-8gb-gaming-x-trio-ampere-graphics-card-rtx-3070-gaming-x-trio # 39
  - https://www.ebuyer.com/1128755-gigabyte-geforce-rtx-3070-8gb-aorus-master-ampere-graphics-card-gv-n3070aorus-m-8gd # 30
  - https://www.ebuyer.com/1124531-asus-geforce-rtx-3070-8gb-dual-oc-ampere-graphics-card-dual-rtx3070-o8g # 20
  - https://www.ebuyer.com/1126282-msi-geforce-rtx-3070-8gb-ventus-3x-oc-ampere-graphics-card-rtx-3070-ventus-3x-oc # 20
  - https://www.ebuyer.com/1127005-asus-geforce-rtx-3070-8gb-gddr6-tuf-gaming-ampere-graphics-card-tuf-rtx3070-8g-gaming # 20
  - https://www.ebuyer.com/1128652-gigabyte-geforce-rtx-3070-8gb-vision-oc-ampere-graphics-card-gv-n3070vision-oc-8gd # 20
  - https://www.ebuyer.com/1126166-gigabyte-geforce-rtx-3070-8gb-eagle-oc-ampere-graphics-card-gv-n3070eagle-oc-8gd # 17
  - https://www.ebuyer.com/1126167-gigabyte-geforce-rtx-3070-8gb-gaming-oc-ampere-graphics-card-gv-n3070gaming-oc-8gd # 9
  - https://www.ebuyer.com/1126107-palit-geforce-rtx-3070-8gb-gamingpro-ampere-graphics-card-ne63070019p2-1041a # 5
  - https://www.ebuyer.com/1126284-msi-geforce-rtx-3070-8gb-ventus-2x-oc-ampere-graphics-card-rtx-3070-ventus-2x-oc # 5
  - https://www.ebuyer.com/1124532-asus-geforce-rtx-3070-8gb-dual-ampere-graphics-card-dual-rtx3070-8g # 5
  - https://www.ebuyer.com/1126110-asus-geforce-rtx-3070-8gb-gddr6-tuf-gaming-oc-ampere-graphics-card-tuf-rtx3070-o8g-gaming # 4
  - https://www.ebuyer.com/1129223-msi-geforce-rtx-3070-suprim-x-8gb-ampere-graphics-card-rtx-3070-suprim-x-8g # 4
  - https://www.ebuyer.com/1136473-msi-geforce-rtx-3070-suprim-8gb-ampere-graphics-card-rtx-3070-suprim-8g # 4
  - https://www.ebuyer.com/1125712-zotac-geforce-rtx-3070-8gb-twin-edge-oc-ampere-graphics-card-zt-a30700h-10p # 3
  - https://www.ebuyer.com/1127006-gigabyte-geforce-rtx-3070-8gb-eagle-ampere-graphics-card-gv-n3070eagle-8gd # 3
  - https://www.ebuyer.com/1126108-palit-geforce-rtx-3070-8gb-gamingpro-oc-ampere-graphics-card-ne63070s19p2-1041a # 2
  - https://www.ebuyer.com/1121363-zotac-geforce-rtx-3070-8gb-twin-edge-ampere-graphics-card-zt-a30700e-10p # 1
  - https://www.ebuyer.com/1124529-asus-geforce-rtx-3070-8gb-rog-strix-oc-ampere-graphics-card-rog-strix-rtx3070-o8g-gaming
  - https://www.ebuyer.com/1129344-palit-geforce-rtx-3070-8gb-gamerock-ampere-graphics-card-ne63070019p2-1040g
  - https://www.ebuyer.com/1129711-kfa2-geforce-rtx-3070-sg-8gb-graphics-card-37nsl6md1gnk
  - https://www.ebuyer.com/1134224-zotac-geforce-rtx-3070-8gb-twin-edge-oc-white-edition-ampere-graphics-zt-a30700j-10p
  - https://www.ebuyer.com/1136701-evga-geforce-rtx-3070-8gb-xc3-ultra-gaming-graphics-card-08g-p5-3755-kr
  - https://www.ebuyer.com/1137258-zotac-geforce-rtx-3070-8gb-amp-holo-ampere-graphics-card-zt-a30700f-10p
  - https://www.ebuyer.com/1138585-evga-geforce-rtx-3070-8gb-ftw3-ultra-gaming-ampere-graphics-card-08g-p5-3767-kr
  - https://www.ebuyer.com/1143975-asus-geforce-rtx-3070-8gb-rog-strix-white-ampere-graphics-card-rog-strix-rtx3070-8g-white
  - https://www.ebuyer.com/1124460-pny-geforce-rtx-3070-8gb-xlr8-gaming-revel-epic-x-ampere-graphics-card-vcg30708tfxppb
  - https://www.ebuyer.com/1124530-asus-geforce-rtx-3070-8gb-rog-strix-ampere-graphics-card-rog-strix-rtx3070-8g-gaming
  - https://www.ebuyer.com/1125853-pny-geforce-rtx-3070-8gb-dual-fan-ampere-graphics-card-vcg30708dfmpb
  - https://www.ebuyer.com/1129436-palit-geforce-rtx-3070-8gb-gamerock-oc-ampere-graphics-card-ne63070h19p2-1040g
  - https://www.ebuyer.com/1138876-asus-geforce-rtx-3070-ekwb-8gb-ampere-graphics-card-rtx3070-8g-ek
...
