---
refresh_interval: 0.10 # seconds
max_price: 550 # GBP
urls:
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3060-ti-gaming-x-trio-8gb-gddr6-graphics-card/rtx3060tigamingxtrio.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-ti-8-gb-gaming-oc-graphics-card-10219305-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-ti-8-gb-vision-oc-graphics-card-10221313-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-ti-8-gb-gaming-oc-pro-graphics-card-10219304-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-ti-8-gb-ventus-2x-oc-graphics-card-10219342-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-ti-8-gb-eagle-graphics-card-10219307-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3060-ti-8-gb-ventus-3x-oc-graphics-card-10219341-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3060-ti-8-gb-dual-oc-graphics-card-10219255-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3060-ti-8-gb-eagle-oc-graphics-card-10219306-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3060-ti-8-gb-xlr8-gaming-revel-edition-graphics-card-10218694-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/processors/amd-ryzen-5-3600-processor-10194811-pdt.html
...
