---
refresh_interval: 1 # seconds
max_price: 770 # GBP
urls:
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-suprim-x-8gb-gddr6-graphics-card/rtx30708gbsuprimx8g.html
  - https://www.novatech.co.uk/products/asus-nvidia-geforce-rtx-3070-dual-oc-8gb-gddr6-graphics-card/dual-rtx3070-o8g.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-graphics-card/rtx3070gamingxtrio.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-graphics-card/rtx3070ventus2xoc.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-graphics-card/rtx3070ventus3xoc.html
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-GAMING-Graphics/dp/B08KHL21CV
  - https://www.amazon.co.uk/ZOTAC-GAMING-GEFORCE-White-Graphics/dp/B08P7ZKQPP
  - https://www.amazon.co.uk/MSI-GeForce-SUPRIM-Gaming-Graphics/dp/B08P37HYZM
  - https://www.amazon.co.uk/MSI-GeForce-GAMING-Gaming-Graphics/dp/B08LNPPCWJ
  - https://www.amazon.co.uk/Gigabyte-AORUS-GeForce-MASTER-Graphics/dp/B08LNY8P5L
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-EAGLE-Graphics/dp/B08KHL2J5X
  - https://www.amazon.co.uk/ASUS-DisplayPort-Axial-tech-Protective-Backplate/dp/B08L8LG4M3
  - https://www.amazon.co.uk/Zotac-GAMING-GEFORCE-3070-HOLO/dp/B08R427DMQ
  - https://www.amazon.co.uk/GIGABYTE-Graphics-WINDFORCE-GV-N3070VISION-OC-8GD/dp/B08M13DXSZ
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-eagle-graphics-card-10217336-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-dual-graphics-card-10215777-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-ventus-2x-oc-graphics-card-10217083-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-gaming-oc-graphics-card-10216240-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-eagle-oc-graphics-card-10216239-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-vision-oc-graphics-card-10218742-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-dual-oc-graphics-card-10215776-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-rog-strix-gaming-oc-graphics-card-10215770-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-rog-strix-gaming-graphics-card-10215775-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-8-gb-tuf-oc-gaming-graphics-card-10217338-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-gaming-x-trio-graphics-card-10217077-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-suprim-graphics-card-10220317-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-ventus-3x-oc-graphics-card-10217078-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/gigabyte-geforce-rtx-3070-8-gb-aorus-master-graphics-card-10218741-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/pny-geforce-rtx-3070-8-gb-xlr8-gaming-revel-edition-graphics-card-10218690-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/asus-geforce-rtx-3070-10-gb-rog-strix-oc-graphics-card-white-10220919-pdt.html
  - https://www.currys.co.uk/gbuk/computing-accessories/components-upgrades/graphics-cards/msi-geforce-rtx-3070-8-gb-suprim-x-graphics-card-10219343-pdt.html
...
