---
refresh_interval: 0.10 # seconds
max_price: 650 # GBP
urls:
  - https://www.aria.co.uk/Products/Components/Graphics+Cards/NVIDIA+GeForce/GeForce+RTX+3060+Ti/Zotac+NVIDIA+GeForce+RTX+3070+8GB+Twin+Edge+OC+White+Edition+Ampere+Graphics+Card?productId=73071
  - https://www.aria.co.uk/Products/Components/Graphics+Cards/NVIDIA+GeForce/GeForce+RTX+3070/Palit+NVIDIA+GeForce+RTX+3070+8GB+GamingPro+Ampere+Graphics+Card?productId=72849
  - https://www.aria.co.uk/Products/Components/Graphics+Cards/NVIDIA+GeForce/GeForce+RTX+3070/ASUS+NVIDIA+GeForce+RTX+3070+8GB+TUF+GAMING+OC+Ampere+Graphics+Card?productId=72939
  - https://www.aria.co.uk/Products/Components/Graphics+Cards/NVIDIA+GeForce/GeForce+RTX+3070/ASUS+NVIDIA+GeForce+RTX+3070+8GB+ROG+Strix+Ampere+Graphics+Card?productId=72937
  - https://www.aria.co.uk/Products/Components/Graphics+Cards/NVIDIA+GeForce/GeForce+RTX+3070/ASUS+NVIDIA+GeForce+RTX+3070+8GB+ROG+Strix+OC+Ampere+Graphics+Card?productId=72936
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-suprim-x-8gb-gddr6-graphics-card/rtx30708gbsuprimx8g.html
  - https://www.novatech.co.uk/products/asus-nvidia-geforce-rtx-3070-dual-oc-8gb-gddr6-graphics-card/dual-rtx3070-o8g.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-graphics-card/rtx3070gamingxtrio.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-graphics-card/rtx3070ventus2xoc.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-graphics-card/rtx3070ventus3xoc.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-dual-8gb-gddr6-pci-express-graphics-card-gx-44n-as.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-tuf-8gb-gddr6-pci-express-graphics-card-gx-450-as.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-tuf-oc-8gb-gddr6-pci-express-graphics-card-gx-451-as.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-rog-strix-8gb-gddr6-pci-express-graphics-card-gx-44q-as.html
  - https://www.overclockers.co.uk/msi-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-pci-express-graphics-card-gx-36e-ms.html
  - https://www.overclockers.co.uk/msi-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-pci-express-graphics-card-gx-36g-ms.html
  - https://www.overclockers.co.uk/gigabyte-geforce-rtx-3070-eagle-8gb-gddr6-pci-express-graphics-card-gx-1ca-gi.html
  - https://www.overclockers.co.uk/gigabyte-geforce-rtx-3070-eagle-oc-8gb-gddr6-pci-express-graphics-card-gx-1c5-gi.html
  - https://www.overclockers.co.uk/gigabyte-geforce-rtx-3070-gaming-oc-8gb-gddr6-pci-express-graphics-card-gx-1c6-gi.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-dual-oc-8gb-gddr6-pci-express-graphics-card-gx-44p-as.html
  - https://www.overclockers.co.uk/asus-geforce-rtx-3070-rog-strix-oc-8gb-gddr6-pci-express-graphics-card-gx-44r-as.html
  - https://www.overclockers.co.uk/gigabyte-geforce-rtx-3070-vision-oc-8gb-gddr6-pci-express-graphics-card-gx-1cb-gi.html
  - https://www.overclockers.co.uk/msi-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-pci-express-graphics-card-gx-36f-ms.html
  - https://www.overclockers.co.uk/palit-geforce-rtx-3070-gaming-pro-8gb-gddr6-pci-express-graphics-card-gx-05b-pl.html
  - https://www.overclockers.co.uk/inno3d-geforce-rtx-3070-twin-x2-oc-8gb-gddr6-pci-express-graphics-card-gx-07f-in.html
  - https://www.overclockers.co.uk/zotac-geforce-rtx-3070-twin-edge-8gb-gddr6-pci-express-graphics-card-gx-121-zt.html
  - https://www.overclockers.co.uk/inno3d-geforce-rtx-3070-ichill-x3-8gb-gddr6-pci-express-graphics-card-gx-07g-in.html
  - https://www.overclockers.co.uk/palit-geforce-rtx-3070-gamerock-oc-8gb-gddr6-pci-express-graphics-card-gx-05j-pl.html
  - https://www.overclockers.co.uk/kfa2-geforce-rtx-3070-sg-8gb-gddr6-pci-express-graphics-card-gx-0ac-kf.html
  - https://www.overclockers.co.uk/pny-geforce-rtx-3070-dual-8gb-gddr6-pci-express-graphics-card-vcg30708dfmpb-gx-06f-pn.html
  - https://www.overclockers.co.uk/palit-geforce-rtx-3070-gaming-pro-oc-8gb-gddr6-pci-express-graphics-card-gx-05c-pl.html
  - https://www.overclockers.co.uk/inno3d-geforce-rtx-3070-ichill-x4-8gb-gddr6-pci-express-graphics-card-gx-07h-in.html
  - https://www.overclockers.co.uk/pny-geforce-rtx-3070-epic-x-xlr8-gaming-8gb-gddr6-pci-express-graphics-card-vcg30708tfxppb-gx-06g-pn.html
  - https://www.overclockers.co.uk/palit-geforce-rtx-3070-gamerock-8gb-gddr6-pci-express-graphics-card-gx-05h-pl.html
  - https://www.overclockers.co.uk/gigabyte-geforce-rtx-3070-master-8gb-gddr6-pci-express-graphics-card-gx-1ce-gi.html
  - https://www.overclockers.co.uk/zotac-geforce-rtx-3070-twin-edge-oc-8gb-gddr6-pci-express-graphics-card-gx-127-zt.html
  - https://www.overclockers.co.uk/corsair-k65-rgb-mini-60-usb-mechanical-gaming-keyboard-cherry-mx-red-black-ch-9194010-uk-kb-0b0-cs.html
  - https://www.scan.co.uk/products/1tb-corsair-force-mp600-m2-2280-pcie-40-x4-nvme-ssd-phison-tlc-3d-nand-4950mb-s-read-4250mb-s-write6
...
