---
refresh_interval: 2 # seconds
max_price: 900 # GBP
urls:
- https://www.ebuyer.com/937375-asus-radeon-rx-5500-xt-dual-evo-oc-8gb-graphics-card-dual-rx5500xt-o8g-evo
- https://www.ebuyer.com/937200-msi-radeon-rx-5500-xt-gaming-x-8gb-graphics-card-rx-5500-xt-gaming-x-8g
...
