---
refresh_interval: 0.10 # seconds
max_price: 650 # GBP
urls:
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-suprim-x-8gb-gddr6-graphics-card/rtx30708gbsuprimx8g.html
  - https://www.novatech.co.uk/products/asus-nvidia-geforce-rtx-3070-dual-oc-8gb-gddr6-graphics-card/dual-rtx3070-o8g.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-gaming-x-trio-8gb-gddr6-graphics-card/rtx3070gamingxtrio.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-2x-oc-8gb-gddr6-graphics-card/rtx3070ventus2xoc.html
  - https://www.novatech.co.uk/products/msi-nvidia-geforce-rtx-3070-ventus-3x-oc-8gb-gddr6-graphics-card/rtx3070ventus3xoc.html
  - https://www.novatech.co.uk/products/11th-generation-intel-core-i5-11600kf-3-90ghz-socket-lga1200-cpuprocessor/bx8070811600kf.html
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-GAMING-Graphics/dp/B08KHL21CV/ref=sr_1_1?dchild=1&keywords=rtx+3070&qid=1618255532&sr=8-1
  - https://www.amazon.co.uk/Gigabyte-GeForce-3070-GAMING-Graphics/dp/B08KHL21CV/ref=sr_1_1?dchild=1&keywords=rtx+3070&qid=1618255532&sr=8-1/dp/B08KHL21CV
  - https://www.amazon.co.uk/dp/B08KHL21CV
...
