---
refresh_interval: 0.1 # seconds
max_price: 650 # GBP
urls:
 - https://www.smythstoys.com/uk/en-gb/video-games-and-tablets/xbox-gaming/xbox-series-x-%7c-s/xbox-series-x-%7c-s-consoles/xbox-series-x-1tb-console/p/192012
 - https://www.smythstoys.com/uk/en-gb/video-games-and-tablets/xbox-gaming/xbox-series-x-%7c-s/xbox-series-x-%7c-s-accessories/xbox-wireless-controller-%e2%80%93-shock-blue/p/192246
 - https://www.argos.co.uk/product/8448262
 - https://www.argos.co.uk/product/8399139
 - https://www.shopto.net/en/xbxhw01-xbox-series-x-p191471/
 - https://www.shopto.net/en/xb1co43-control-p66010/
 - https://www.simplygames.com/p/xbox-series-x-console-xbox-one
 - https://www.simplygames.com/p/xbox-wireless-controller---shock-blue-xbox-series-x
 - https://www.amazon.co.uk/Xbox-RRT-00007-Series-X/dp/B08H93GKNJ
 - https://www.box.co.uk/RRT-00007-Xbox-Series-X-Console_3201195.html
 - https://www.johnlewis.com/p5151987
 - https://www.johnlewis.com/xbox-wireless-controller/carbon-black/p5220059
 - https://www.ebuyer.com/1133948-xbox-series-x-console-rrt-00007
...
